In [67]:
import numpy as np
import random

In [68]:
L=20

psi=np.zeros((3,L,L), dtype=complex)

#psi[0]= psi_{-1} #
#psi[2]= psi_{+1} #

dx=0.1
dt=dx/10

cs=-1
cn=1
mu=1
M=1

q=-1


print(len(psi))
print(len(psi[0]))
print(len(psi[0,0]))



3
20
20


In [69]:
#for i in range(len(psi)):
#    for j in range(0,len(psi[0])):
#        for k in range(0,len(psi[0,0])):
#            psi[i,j,k]=random.random()+random.random()*1j

psi[0]=1
psi[1]=0
psi[2]=0

psi=psi/np.sqrt(np.absolute(psi[0])**2+np.absolute(psi[1])**2+np.absolute(psi[2])**2)

print(psi)

psi_in=psi


[[[1.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 1.+0.j]
  ...
  [1.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 1.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  ...
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  ...
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]]]


In [70]:
def norm(x) :
    return np.sqrt(abs(x[0])**2+abs(x[1])**2+abs(x[2])**2)

def normsq(x) :
    return abs(x[0])**2+abs(x[1])**2+abs(x[2])**2



print(norm(psi))


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [71]:
def sx(x) :
    return (1/np.sqrt(2))*(np.conjugate(x[2])*x[1]+np.conjugate(x[1])*x[2]+np.conjugate(x[1])*x[0]+np.conjugate(x[0])*x[1])

def sy(x) :
    return (1j/np.sqrt(2))*(-np.conjugate(x[2])*x[1]+np.conjugate(x[1])*x[2]-np.conjugate(x[1])*x[0]+np.conjugate(x[0])*x[1])

def sz(x) :
    return np.conjugate(x[2])*x[2]-np.conjugate(x[0])*x[0]

In [72]:
def devx(x) :
    y=np.zeros((len(x),len(x[0]),len(x[0,0])), dtype=complex)
    for i in range(len(x)):
        for j in range(1,len(x[0])-1):
            for k in range(0,len(x[0,0])):
                y[i,j,k]=(x[i,j+1,k]-x[i,j-1,k])/(2*dx)
        for k in range(0,len(x[0,0])):
            y[i,0,k]=(x[i,1,k]-x[i,0,k])/(dx)
            y[i,len(x[0])-1,k]=(x[i,len(x[0])-1,k]-x[i,len(x[0])-2,k])/(dx)
        
    return y


def devy(x) :
    y=np.zeros((len(x),len(x[0]),len(x[0,0])), dtype=complex)
    for i in range(len(x)):
        for j in range(0,len(x[0])):
            for k in range(1,len(x[0,0])-1):
                y[i,j,k]=(x[i,j,k+1]-x[i,j,k-1])/(2*dx)
        for j in range(0,len(x[0])):
            y[i,j,0]=(x[i,j,1]-x[i,j,0])/(dx)
            y[i,j,len(x[0,0])-1]=(x[i,j,len(x[0,0])-1]-x[i,j,len(x[0,0])-2])/(dx)
        
    return y





'''
def devx(x) :
    y=np.zeros((len(x),len(x[0]),len(x[0,0])), dtype=complex)
    for i in range(len(x)):
        for j in range(2,len(x[0])-2):
            for k in range(0,len(x[0,0])):
                y[i,j,k]=(-x[i,j+2,k]+8*x[i,j+1,k]-8*x[i,j-1,k]+x[i,j-2,k])/(12*dx)
        for k in range(0,len(x[0,0])):
            y[i,1,k]=(x[i,2,k]-x[i,0,k])/(2*dx)
            y[i,len(x[0])-2,k]=(x[i,len(x[0])-1,k]-x[i,len(x[0])-3,k])/(2*dx)
            y[i,0,k]=(x[i,1,k]-x[i,0,k])/(dx)
            y[i,len(x[0])-1,k]=(x[i,len(x[0])-1,k]-x[i,len(x[0])-2,k])/(dx)
        
    return y

def devy(x) :
    y=np.zeros((len(x),len(x[0]),len(x[0,0])), dtype=complex)
    for i in range(len(x)):
        for j in range(0,len(x[0])):
            for k in range(2,len(x[0,0])-2):
                y[i,j,k]=(-x[i,j,k+2]+8*x[i,j,k+1]-8*x[i,j,k-1]+x[i,j,k-2])/(12*dx)
        for j in range(0,len(x[0])):
            y[i,j,1]=(x[i,j,2]-x[i,j,0])/(2*dx)
            y[i,j,len(x[0])-2]=(x[i,j,len(x[0])-1]-x[i,j,len(x[0])-3])/(2*dx)
            y[i,j,0]=(x[i,j,1]-x[i,j,0])/(dx)
            y[i,j,len(x[0])-1]=(x[i,j,len(x[0])-1]-x[i,j,len(x[0])-2])/(dx)

    return y
'''

'\ndef devx(x) :\n    y=np.zeros((len(x),len(x[0]),len(x[0,0])), dtype=complex)\n    for i in range(len(x)):\n        for j in range(2,len(x[0])-2):\n            for k in range(0,len(x[0,0])):\n                y[i,j,k]=(-x[i,j+2,k]+8*x[i,j+1,k]-8*x[i,j-1,k]+x[i,j-2,k])/(12*dx)\n        for k in range(0,len(x[0,0])):\n            y[i,1,k]=(x[i,2,k]-x[i,0,k])/(2*dx)\n            y[i,len(x[0])-2,k]=(x[i,len(x[0])-1,k]-x[i,len(x[0])-3,k])/(2*dx)\n            y[i,0,k]=(x[i,1,k]-x[i,0,k])/(dx)\n            y[i,len(x[0])-1,k]=(x[i,len(x[0])-1,k]-x[i,len(x[0])-2,k])/(dx)\n        \n    return y\n\ndef devy(x) :\n    y=np.zeros((len(x),len(x[0]),len(x[0,0])), dtype=complex)\n    for i in range(len(x)):\n        for j in range(0,len(x[0])):\n            for k in range(2,len(x[0,0])-2):\n                y[i,j,k]=(-x[i,j,k+2]+8*x[i,j,k+1]-8*x[i,j,k-1]+x[i,j,k-2])/(12*dx)\n        for j in range(0,len(x[0])):\n            y[i,j,1]=(x[i,j,2]-x[i,j,0])/(2*dx)\n            y[i,j,len(x[0])-2]=(x[i,j,le

In [73]:
def dev2x(x) :
    y=np.zeros((len(x),len(x[0]),len(x[0,0])), dtype=complex)
    for i in range(len(x)):
        for j in range(1,len(x[0])-1):
            for k in range(0,len(x[0,0])):
                y[i,j,k]=(x[i,j+1,k]+x[i,j-1,k]-2*x[i,j,k])/(dx*dx)
        for k in range(0,len(x[0,0])):
            y[i,0,k]=(x[i,1,k]-devx(x)[i,0,k]*dx-x[i,0,k])*2/(dx**2)
            y[i,len(x[0])-1,k]=(x[i,len(x[0])-2,k]+devx(x)[i,len(x[0])-1,k]*dx-x[i,len(x[0])-1,k])*2/(dx**2)
    return y

def dev2y(x) :
    y=np.zeros((len(x),len(x[0]),len(x[0,0])), dtype=complex)
    for i in range(len(x)):
        for j in range(0,len(x[0])):
            for k in range(1,len(x[0,0])-1):
                y[i,j,k]=(x[i,j,k+1]+x[i,j,k-1]-2*x[i,j,k])/(dx*dx)
        for j in range(0,len(x[0])):
            y[i,j,0]=(x[i,j,1]-devy(x)[i,j,0]*dx-x[i,j,0])*2/(dx**2)
            y[i,j,len(x[0])-1]=(x[i,j,len(x[0])-2]-devy(x)[i,j,len(x[0])-1]*dx-x[i,j,len(x[0])-1])*2/(dx**2)
    return y






'''

def dev2x(x) :
    y=np.zeros((len(x),len(x[0]),len(x[0,0])), dtype=complex)
    for i in range(len(x)):
        for j in range(2,len(x[0])-2):
            for k in range(0,len(x[0,0])):
                y[i,j,k]=(-x[i,j+2,k]+16*x[i,j+1,k]-30*x[i,j,k]+16*x[i,j-1,k]-x[i,j-2,k])/(12*dx**2)
        for k in range(0,len(x[0,0])):
            y[i,1,k]=(x[i,2,k]+x[i,0,k]-2*x[i,1,k])/(dx**2)
            y[i,len(x[0])-2,k]=(x[i,len(x[0])-1,k]+x[i,len(x[0])-3,k]-2*x[i,len(x[0])-2,k])/(dx**2)
            y[i,0,k]=(x[i,2,k]-2*x[i,1,k]+x[i,0,k])/(dx**2)
            y[i,len(x[0])-1,k]=(x[i,len(x[0])-1,k]-2*x[i,len(x[0])-2,k]+x[i,len(x[0])-3,k])/(dx**2)
    return y

def dev2y(x) :
    y=np.zeros((len(x),len(x[0]),len(x[0,0])), dtype=complex)
    for i in range(len(x)):
        for j in range(0,len(x[0])):
            for k in range(2,len(x[0])-2):
                y[i,j,k]=(-x[i,j,k+2]+16*x[i,j,k+1]-30*x[i,j,k]+16*x[i,j,k-1]-x[i,j,k-2])/(12*dx**2)
        for j in range(0,len(x[0])):
            y[i,j,1]=(x[i,j,2]+x[i,j,0]-2*x[i,j,1])/(dx**2)
            y[i,j,len(x[0])-2]=(x[i,j,len(x[0])-1]+x[i,j,len(x[0])-3]-2*x[i,j,len(x[0])-2])/(dx**2)
            y[i,j,0]=(x[i,j,2]-2*x[i,j,1]+x[i,j,0])/(dx**2)
            y[i,j,len(x[0])-1]=(x[i,j,len(x[0])-1]-2*x[i,j,len(x[0])-2]+x[i,j,len(x[0])-3])/(dx**2)
    return y

'''
def lap(x) :
    return dev2x(x)+dev2y(x)

In [74]:
def Egp(x) :
    y=0
    
    DxX=devx(x)
    DyX=devy(x)
    Sx=sx(x)
    Sy=sy(x)
    Sz=sz(x)
    

    for j in range(len(x[0])) :
        for k in range(len(x[0,0])) :
            y=y+(dx**2)*(1/(2*M))*(np.absolute(DxX[0,j,k])**2+np.absolute(DyX[0,j,k])**2)
            y=y+(dx**2)*(1/(2*M))*(np.absolute(DxX[1,j,k])**2+np.absolute(DyX[1,j,k])**2)
            y=y+(dx**2)*(1/(2*M))*(np.absolute(DxX[2,j,k])**2+np.absolute(DyX[2,j,k])**2)
            y=y+(dx**2)*(cs/2)*(Sx[j,k]**2+Sy[j,k]**2+Sz[j,k]**2)
            #y=y+(dx**2)*((cn/2)*(normsq(x)[j,k]**2)-mu*normsq(x)[j,k])
            y=y+(dx**2)*q*(np.absolute(x[2,j,k])**2+np.absolute(x[0,j,k])**2)

    return y


In [75]:
print(Egp(psi))

(-5.999999999999909+0j)


In [76]:
'''
def evo0(x) :
    return -1j*(-(1/(2*M))*lap(x)[0]+cs*(sx(x)*(1/np.sqrt(2))*(x[1])+sy(x)*(-1j/np.sqrt(2))*(x[1])+sz(x)*x[0])+q*x[0]+cn*normsq(x)*x[0]-mu*x[0])

def evo1(x) :
    return -1j*(-(1/(2*M))*lap(x)[1]+cs*(sx(x)*(1/np.sqrt(2))*(x[0]+x[2])+sy(x)*(1j/np.sqrt(2))*(x[0]-x[2]))+cn*normsq(x)*x[1]-mu*x[1])

def evo2(x) :
    return -1j*(-(1/(2*M))*lap(x)[2]+cs*(sx(x)*(1/np.sqrt(2))*(x[1])+sy(x)*(1j/np.sqrt(2))*(x[1])+sz(x)*(-x[2]))+q*x[2]+cn*normsq(x)*x[2]-mu*x[2])
'''



def evo0(x) :
    return -1j*(-(1/(2*M))*lap(x)[0]+cs*(sx(x)*(1/np.sqrt(2))*(x[1])+sy(x)*(-1j/np.sqrt(2))*(x[1])+sz(x)*x[0])+q*x[0])

def evo1(x) :
    return -1j*(-(1/(2*M))*lap(x)[1]+cs*(sx(x)*(1/np.sqrt(2))*(x[0]+x[2])+sy(x)*(1j/np.sqrt(2))*(x[0]-x[2])))

def evo2(x) :
    return -1j*(-(1/(2*M))*lap(x)[2]+cs*(sx(x)*(1/np.sqrt(2))*(x[1])+sy(x)*(1j/np.sqrt(2))*(x[1])+sz(x)*(-x[2]))+q*x[2])



In [77]:
N=100

k1=np.zeros((len(psi),len(psi[0]),len(psi[0,0])), dtype=complex)
k2=np.zeros((len(psi),len(psi[0]),len(psi[0,0])), dtype=complex)
k3=np.zeros((len(psi),len(psi[0]),len(psi[0,0])), dtype=complex)
k4=np.zeros((len(psi),len(psi[0]),len(psi[0,0])), dtype=complex)


for t in range(N):


    k1[0]=evo0(psi)
    k1[1]=evo1(psi)
    k1[2]=evo2(psi)

    k2[0]=evo0(psi+(dt/2)*k1)
    k2[1]=evo1(psi+(dt/2)*k1)
    k2[2]=evo2(psi+(dt/2)*k1)

    k3[0]=evo0(psi+(dt/2)*k2)
    k3[1]=evo1(psi+(dt/2)*k2)
    k3[2]=evo2(psi+(dt/2)*k2)

    k4[0]=evo0(psi+(dt)*k3)
    k4[1]=evo1(psi+(dt)*k3)
    k4[2]=evo2(psi+(dt)*k3)
    
    psi=psi+dt*(k1+2*k2+2*k3+k4)/6

    psi=psi/np.sqrt(np.absolute(psi[0])**2+np.absolute(psi[1])**2+np.absolute(psi[2])**2)

    
    print(Egp(psi))


(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999909+0j)
(-5.999999999999

KeyboardInterrupt: 

In [78]:
print(psi)

[[[1.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 1.+0.j]
  ...
  [1.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 1.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  ...
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  ...
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]]]


In [79]:
print(norm(psi))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.